using UnityEngine;

namespace More.Settings_system
{
	public static class SettingsKeyCodeExtensions
	{
		public static string ToFriendlyString(this KeyCode kc)
		{
			return kc switch
			{
				UnityEngine.KeyCode.A => "A",
				UnityEngine.KeyCode.B => "B",
				UnityEngine.KeyCode.C => "C",
				UnityEngine.KeyCode.D => "D",
				UnityEngine.KeyCode.E => "E",
				UnityEngine.KeyCode.F => "F",
				UnityEngine.KeyCode.G => "G",
				UnityEngine.KeyCode.H => "H",
				UnityEngine.KeyCode.I => "I",
				UnityEngine.KeyCode.J => "J",
				UnityEngine.KeyCode.K => "K",
				UnityEngine.KeyCode.L => "L",
				UnityEngine.KeyCode.M => "M",
				UnityEngine.KeyCode.N => "N",
				UnityEngine.KeyCode.O => "O",
				UnityEngine.KeyCode.P => "P",
				UnityEngine.KeyCode.Q => "Q",
				UnityEngine.KeyCode.R => "R",
				UnityEngine.KeyCode.S => "S",
				UnityEngine.KeyCode.T => "T",
				UnityEngine.KeyCode.U => "U",
				UnityEngine.KeyCode.V => "V",
				UnityEngine.KeyCode.W => "W",
				UnityEngine.KeyCode.X => "X",
				UnityEngine.KeyCode.Y => "Y",
				UnityEngine.KeyCode.Z => "Z",

				UnityEngine.KeyCode.Alpha0 => "0",
				UnityEngine.KeyCode.Alpha1 => "1",
				UnityEngine.KeyCode.Alpha2 => "2",
				UnityEngine.KeyCode.Alpha3 => "3",
				UnityEngine.KeyCode.Alpha4 => "4",
				UnityEngine.KeyCode.Alpha5 => "5",
				UnityEngine.KeyCode.Alpha6 => "6",
				UnityEngine.KeyCode.Alpha7 => "7",
				UnityEngine.KeyCode.Alpha8 => "8",
				UnityEngine.KeyCode.Alpha9 => "9",

				UnityEngine.KeyCode.F1 => "F1",
				UnityEngine.KeyCode.F2 => "F2",
				UnityEngine.KeyCode.F3 => "F3",
				UnityEngine.KeyCode.F4 => "F4",
				UnityEngine.KeyCode.F5 => "F5",
				UnityEngine.KeyCode.F6 => "F6",
				UnityEngine.KeyCode.F7 => "F7",
				UnityEngine.KeyCode.F8 => "F8",
				UnityEngine.KeyCode.F9 => "F9",
				UnityEngine.KeyCode.F10 => "F10",
				UnityEngine.KeyCode.F11 => "F11",
				UnityEngine.KeyCode.F12 => "F12",

				UnityEngine.KeyCode.Minus => "-",
				UnityEngine.KeyCode.Equals => "=",
				UnityEngine.KeyCode.BackQuote => "`",

				UnityEngine.KeyCode.Tab => "Tab",
				UnityEngine.KeyCode.LeftShift => "LShift",
				UnityEngine.KeyCode.RightShift => "RShift",
				UnityEngine.KeyCode.LeftControl => "LCtrl",
				UnityEngine.KeyCode.RightControl => "RCtrl",
				UnityEngine.KeyCode.LeftAlt => "LAlt",
				UnityEngine.KeyCode.RightAlt => "RAlt",
				UnityEngine.KeyCode.Space => "Space",

				UnityEngine.KeyCode.LeftBracket => "[",
				UnityEngine.KeyCode.RightBracket => "]",
				UnityEngine.KeyCode.Semicolon => ";",
				UnityEngine.KeyCode.Quote => "'",
				UnityEngine.KeyCode.Comma => ",",
				UnityEngine.KeyCode.Period => ".",
				UnityEngine.KeyCode.Slash => "/",
				UnityEngine.KeyCode.Backslash => "\\",
				UnityEngine.KeyCode.CapsLock => "CLock",
				UnityEngine.KeyCode.Backspace => "BSpace",

				UnityEngine.KeyCode.UpArrow => "↑",
				UnityEngine.KeyCode.DownArrow => "↓",
				UnityEngine.KeyCode.LeftArrow => "←",
				UnityEngine.KeyCode.RightArrow => "→",
				UnityEngine.KeyCode.Insert => "Ins",
				UnityEngine.KeyCode.Delete => "Del",
				UnityEngine.KeyCode.Home => "Home",
				UnityEngine.KeyCode.End => "End",
				UnityEngine.KeyCode.PageUp => "PgUp",
				UnityEngine.KeyCode.PageDown => "PgDn",

				UnityEngine.KeyCode.Mouse0 => "LMB",
				UnityEngine.KeyCode.Mouse1 => "RMB",
				UnityEngine.KeyCode.Mouse2 => "MMB",
				UnityEngine.KeyCode.Mouse3 => "M4",
				UnityEngine.KeyCode.Mouse4 => "M5",
				UnityEngine.KeyCode.Mouse5 => "M6",
				UnityEngine.KeyCode.Mouse6 => "M7",

				_ => ""
			};
		}

		public static KeyCode ToKeyCode(this string s)
		{
			return s switch
			{
				"A" => UnityEngine.KeyCode.A,
				"B" => UnityEngine.KeyCode.B,
				"C" => UnityEngine.KeyCode.C,
				"D" => UnityEngine.KeyCode.D,
				"E" => UnityEngine.KeyCode.E,
				"F" => UnityEngine.KeyCode.F,
				"G" => UnityEngine.KeyCode.G,
				"H" => UnityEngine.KeyCode.H,
				"I" => UnityEngine.KeyCode.I,
				"J" => UnityEngine.KeyCode.J,
				"K" => UnityEngine.KeyCode.K,
				"L" => UnityEngine.KeyCode.L,
				"M" => UnityEngine.KeyCode.M,
				"N" => UnityEngine.KeyCode.N,
				"O" => UnityEngine.KeyCode.O,
				"P" => UnityEngine.KeyCode.P,
				"Q" => UnityEngine.KeyCode.Q,
				"R" => UnityEngine.KeyCode.R,
				"S" => UnityEngine.KeyCode.S,
				"T" => UnityEngine.KeyCode.T,
				"U" => UnityEngine.KeyCode.U,
				"V" => UnityEngine.KeyCode.V,
				"W" => UnityEngine.KeyCode.W,
				"X" => UnityEngine.KeyCode.X,
				"Y" => UnityEngine.KeyCode.Y,
				"Z" => UnityEngine.KeyCode.Z,

				"0" => UnityEngine.KeyCode.Alpha0,
				"1" => UnityEngine.KeyCode.Alpha1,
				"2" => UnityEngine.KeyCode.Alpha2,
				"3" => UnityEngine.KeyCode.Alpha3,
				"4" => UnityEngine.KeyCode.Alpha4,
				"5" => UnityEngine.KeyCode.Alpha5,
				"6" => UnityEngine.KeyCode.Alpha6,
				"7" => UnityEngine.KeyCode.Alpha7,
				"8" => UnityEngine.KeyCode.Alpha8,
				"9" => UnityEngine.KeyCode.Alpha9,

				"F1" => UnityEngine.KeyCode.F1,
				"F2" => UnityEngine.KeyCode.F2,
				"F3" => UnityEngine.KeyCode.F3,
				"F4" => UnityEngine.KeyCode.F4,
				"F5" => UnityEngine.KeyCode.F5,
				"F6" => UnityEngine.KeyCode.F6,
				"F7" => UnityEngine.KeyCode.F7,
				"F8" => UnityEngine.KeyCode.F8,
				"F9" => UnityEngine.KeyCode.F9,
				"F10" => UnityEngine.KeyCode.F10,
				"F11" => UnityEngine.KeyCode.F11,
				"F12" => UnityEngine.KeyCode.F12,

				"-" => UnityEngine.KeyCode.Minus,
				"=" => UnityEngine.KeyCode.Equals,
				"`" => UnityEngine.KeyCode.BackQuote,

				"Tab" => UnityEngine.KeyCode.Tab,
				"LShift" => UnityEngine.KeyCode.LeftShift,
				"RShift" => UnityEngine.KeyCode.RightShift,
				"LCtrl" => UnityEngine.KeyCode.LeftControl,
				"RCtrl" => UnityEngine.KeyCode.RightControl,
				"LAlt" => UnityEngine.KeyCode.LeftAlt,
				"RAlt" => UnityEngine.KeyCode.RightAlt,
				"Space" => UnityEngine.KeyCode.Space,

				"[" => UnityEngine.KeyCode.LeftBracket,
				"]" => UnityEngine.KeyCode.RightBracket,
				";" => UnityEngine.KeyCode.Semicolon,
				"'" => UnityEngine.KeyCode.Quote,
				"," => UnityEngine.KeyCode.Comma,
				"." => UnityEngine.KeyCode.Period,
				"/" => UnityEngine.KeyCode.Slash,
				"\\" => UnityEngine.KeyCode.Backslash,
				"CLock" => UnityEngine.KeyCode.CapsLock,
				"BSpace" => UnityEngine.KeyCode.Backspace,

				"↑" => UnityEngine.KeyCode.UpArrow,
				"↓" => UnityEngine.KeyCode.DownArrow,
				"←" => UnityEngine.KeyCode.LeftArrow,
				"→" => UnityEngine.KeyCode.RightArrow,
				"Ins" => UnityEngine.KeyCode.Insert,
				"Del" => UnityEngine.KeyCode.Delete,
				"Home" => UnityEngine.KeyCode.Home,
				"End" => UnityEngine.KeyCode.End,
				"PgUp" => UnityEngine.KeyCode.PageUp,
				"PgDn" => UnityEngine.KeyCode.PageDown,

				"LMB" => UnityEngine.KeyCode.Mouse0,
				"RMB" => UnityEngine.KeyCode.Mouse1,
				"MMB" => UnityEngine.KeyCode.Mouse2,
				"M4" => UnityEngine.KeyCode.Mouse3,
				"M5" => UnityEngine.KeyCode.Mouse4,
				"M6" => UnityEngine.KeyCode.Mouse5,
				"M7" => UnityEngine.KeyCode.Mouse6,

				_ => UnityEngine.KeyCode.None
			};
		}
	}
}
